version: "3.9"
services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    restart: always

  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

volumes:
  db_data:
  redis_data:
